# Generated by Django 6.0.3 on 2026-04-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
