# Generated by Django 6.0.3 on 2026-04-09 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10)),
                ('department', models.CharField(default='General', max_length=50)),
                ('floor', models.CharField(default='One', max_length=20)),
                ('status', models.CharField(choices=[('Occupied', 'Occupied'), ('Available', 'Available'), ('Maintenance', 'Maintenance'), ('Reserved', 'Reserved')], default='Available', max_length=20)),
                ('patient', models.ForeignKey(blank=True, limit_choices_to={'status': 'Admitted'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
            ],
        ),
    ]
