# Generated by Django 6.0.3 on 2026-04-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_alter_bed_bed_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('Occupied', 'Occupied'), ('Available', 'Available'), ('Reserved', 'Reserved')], default='Available', max_length=20),
        ),
    ]
