# Generated by Django 6.0.3 on 2026-04-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
