# Generated by Django 6.0.3 on 2026-04-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('patients_count', models.IntegerField()),
                ('experience_years', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
